package com.lemi.mario.appmanager.error;

/**
 * Created by zhou on 14-12-8.
 */
public enum Error {
  NO_ERROR,
  UNKNOWN,
  IO_ERROR,
  TIMEOUT_ERROR,
  INTERRUPTED_ERROR,
  INCONSISTENT_CERTIFICATES,
  INSUFFICIENT_STORAGE,
  FILE_NO_EXIST_ERROR,
  PACKAGE_PARSE_ERROR,
  PACKAGE_NAME_ERROR,
  PACKAGE_ALREADY_EXIST,
  INSTALL_FAILED_DEXOPT,
  INSTALL_FAILED_INTERNAL_ERROR,
  INSTALL_FAILED_INVALID_INSTALL_LOCATION,
  INSTALL_FAILED_MEDIA_UNAVAILABLE,
  INSTALL_FAILED_MISSING_FEATURE,
  INSTALL_FAILED_MISSING_SHARED_LIBRARY,
  INSTALL_FAILED_NO_SHARED_USER,
  INSTALL_FAILED_NEWER_SDK,
  INSTALL_FAILED_REPLACE_COULDNT_DELETE,
  INSTALL_FAILED_SHARED_USER_INCOMPATIBLE,
  INSTALL_FAILED_TEST_ONLY,
  INSTALL_FAILED_UPDATE_INCOMPATIBLE,
  NO_APP_ERROR,
  NO_PERMISSION_ERROR
}
